### ISSUE TITLE
How to ignore payment method and go directly to credit card view controller ?

### ISSUE THREAD

**Issue by yuhny** [veritrans/Veritrans-ios-sdk#110]
Hi,

I'm trying to apply the SDK to my application and I get a problem that I just want to make user confused with the payment methods list when he/she starts a payment; thus, I just want show directly Credit Card viewcontroller to allow user be able to pay quickly with his/her card.

Is there any way to do that in the SDK? or is there any way to filter out the list of payment methods?

Many Thanks

**Comment by dindatisi** [comment]
hi @yuhny , 

Unfortunately, currently there's no way to modify the flow/skip the payment method list page if you're using UI flow. However, we're on the verge of releasing an upgraded version of the SDK. So if you can wait for another 1-2 weeks, you can have that enhancement in our new sdk.

**Comment by yuhny** [comment]
@dindatisi 

That's great to have your quick response, will looking forward to new version.

Many thanks

**Comment by dindatisi** [comment]
hi @yuhny 
Sorry for the wait. Our latest iOS SDK version is already on master branch. Kindly check it out.
