### ISSUE TITLE
Delegate

### ISSUE THREAD

**Issue by prororgeek** [veritrans/Veritrans-ios-sdk#111]
When i am install pods in my code, I am not getting delegate method and it is crash give me suggestion as soon as possible.

**Comment by dindatisi** [comment]
Hi @prororgeek in a few more days we will release a new version of veritrans iOS SDK and the current version will no longer be supported. Unless you're in such a hurry, we'd suggest you to wait and we'll let you know when the new version is available :)

Thanks

**Comment by prororgeek** [comment]
thanks dindatisi

how much time take this ? Because i have not more days

**Comment by dindatisi** [comment]
Hi @prororgeek sorry for making you wait. Our latest iOS SDK version is already on master branch. Kindly check it out.

**Comment by prororgeek** [comment]
Hi @dindatisi , I am try to implement new repository but i am getting same error, I have also try to implement by providing you reference url. Please see docx, I have also attached it.
[Document for Veritrans.pdf](https://github.com/veritrans/Veritrans-ios-sdk/files/591878/Document.for.Veritrans.pdf)

**Comment by jukiginanjar** [comment]
Hi @prororgeek , it seems that you still using the old SDK v0.1.8, our latest version is v1.0.6
<img width="239" alt="screen shot 2016-11-16 at 11 22 39" src="https://cloud.githubusercontent.com/assets/7435655/20334720/08fd0940-abef-11e6-8120-ded373ca83bb.png">

If your Podfile is ok, maybe it cached by system, you can try to clear your cocoapods cache

```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by prororgeek** [comment]
Hello 
I have change all thing 
when i run with your credential like client key it is working. but when i am running with my client key that is "VT-client-yK1eGfkk7PSKd2l5" i am getting this error "Error Domain=error.veritrans.co.id Code=411 "Transaksi Anda ditolak. Silakan ulangi lagi atau coba dengan metode pembayaran lain." "

My merchant Id is :- M097816

I am getting this error when try credit card payment process 

Please have a look and let me know where is problem

**Comment by vanbungkring** [comment]
@prororgeek is that on production?

**Comment by prororgeek** [comment]
No It is on Sandbox

**Comment by dindatisi** [comment]
hi @prororgeek I can confirm that you're using the correct sandbox client key for your merchant ID. Please make sure that you already setup your server based on this [reference](https://github.com/veritrans/veritrans-android/wiki/Implementation-for-Merchant-Server)

Let us know if you still got the same problem.

Thanks

**Comment by prororgeek** [comment]
I did not get you above suggestion

I am talking about iOS Implement and i was following all think as per you reference :- https://github.com/veritrans/Veritrans-ios-sdk/blob/master/MidtransKit/code_usage.md

**Comment by dindatisi** [comment]
Hi, I suspect your issue happened because you don't yet have server side implementation, so that the client & server keys doesn't match. On https://github.com/veritrans/Veritrans-ios-sdk/blob/master/MidtransKit/code_usage.md, if you read through the "Setup" section, there's a link to [this wiki](https://github.com/veritrans/Veritrans-ios-sdk/wiki/Getting-started-with-the-Veritrans-SDK). 

Basically for the SDK to work, you need to have a server side implementation. That's where you setup your server key so that your client & server key will match.

**Comment by prororgeek** [comment]
Whenever you want.
I am ready Between  10:00 AM to 09:00 PM IST. Please let me know how we connect and when.

**Comment by dindatisi** [comment]
Ok. Can I have your email? Lets do the call via google hangout on Tuesday. I'll let you know the details once I send out the call invitation. Thanks

**Comment by prororgeek** [comment]
Sorry Can be possible today 
because it is very urgent, I have to upload app on App Store 
that why i am telling you

My Email id is :- samosys.tech@gmail.com

**Comment by dindatisi** [comment]
i sent you an email. please check

**Comment by prororgeek** [comment]
I got it thanks 
Can we make a call on Skype
