### ISSUE TITLE
MidtransConfig on Cocoapod

### ISSUE THREAD

**Issue by infotech-michael** [veritrans/Veritrans-ios-sdk#120]
i've put pod 'MidtransKit' on my podfile
when i check, there's no MidtransConfig class / file on pod project

and when i can't try the demo after i install the pos
Demo Project Error
![screen shot 2016-10-26 at 4 07 42 pm](https://cloud.githubusercontent.com/assets/23073553/19719988/64c24786-9b96-11e6-8ad6-d6d52e59e17e.png)

**Comment by jukiginanjar** [comment]
you can try on README, at point 3

https://github.com/veritrans/Veritrans-ios-sdk/blob/master/README.md

**Comment by infotech-michael** [comment]
sorry, I missed that point

**Comment by infotech-michael** [comment]
Dear Nanang,
I missed that point.

How about missing MidtransConfig on MidtransKit cocoapod ?

Regards,

Michael

**Comment by vanbungkring** [comment]
Hi Michael, let me help you,but first what version of pod u use?
