### ISSUE TITLE
Custom Font become unrecognized

### ISSUE THREAD

**Issue by infotech-michael** [veritrans/Veritrans-ios-sdk#122]
I'm using custom icon font. after i use MidtransKit my icon become ?(questionmark).
After i search there's a function in your cocoapod that make my custom font didnt recognized.

on UIFont+IBCustomFonts.m
+ (NSString *)mapSystemFontWithName:(NSString *)fontName size:(CGFloat)fontSize;

but when i return [UIFont fontWithName:fontName size:fontSize];
it cause terrible bug

Any idea ?

**Comment by jukiginanjar** [comment]
what version do you use? @infotech-michael

**Comment by jukiginanjar** [comment]
FYI this is the map function
```
+ (NSString *)mapSystemFontWithName:(NSString *)fontName size:(CGFloat)fontSize{
    if ([fontName isEqualToString:@"SourceSansPro-Regular"]) {
        return [[MidtransUIThemeManager shared].themeFont fontNameRegular];
    } else if ([fontName isEqualToString:@"SourceSansPro-Bold"]) {
        return [[MidtransUIThemeManager shared].themeFont fontNameBold];
    } else if ([fontName isEqualToString:@"SourceSansPro-Light"]) {
        return [[MidtransUIThemeManager shared].themeFont fontNameLight];
    } else if ([fontName isEqualToString:@"SourceSansPro-Semibold"]) {
        return [[MidtransUIThemeManager shared].themeFont fontNameRegular];
    } else {
        return nil;
    }
}
```
used to map SDK's default font to the configured custom font @infotech-michael 

if you can help me to reproduce the bug, that would be nice 😃

**Comment by infotech-michael** [comment]
I'm Using MidtransCoreKit (1.0.2) &  MidtransKit (1.0.2).
That function makes my custom font (icon font) become questionmark(?) characters.
Currently I comment the initialize function on that Category

**Comment by infotech-michael** [comment]
I'm using https://github.com/PrideChung/FontAwesomeKit to use Icon
when i use MidtransKit CocoaPod, all FontAwesomeKit icon become questionmark(?).
You could try it.

**Comment by jukiginanjar** [comment]
now I can reproduce it, i'll get back to you after I've resolved this or I need your help @infotech-michael

**Comment by jukiginanjar** [comment]
Hi @infotech-michael , i've updated my custom font helper & hope it can solved your issue

you can try on cocoapods version 1.0.3
