### ISSUE TITLE
Unable to set up merchantServer URL for 2-Click payments

### ISSUE THREAD

**Issue by EonKid** [veritrans/Veritrans-ios-sdk#127]
I have to implement transaction using credit card . Using example code provided by you .How can isetup merchant URL .Provide some tutorial related to iOS sdk.
I have getting NULL response for the credit card payment 
=================
[[MidtransMerchantClient sharedClient] requestPaymentlistWithToken:self.transactionToken.tokenId
                                                                completion:^(MidtransPaymentRequestResponse * _Nullable response, NSError * _Nullable error)
         {
             [MBProgressHUD hideHUDForView:self.view animated:YES];
             self.title = response.merchantData.displayName;
             if (response) {
                 NSInteger grandTotalAmount = [response.transactionData.transactionDetails.amount integerValue];
                 // [self.tableView reloadData];
                 self.paymentRequestResponse = response;
                 if (self.paymentRequestResponse.transactionData.enabledPayments.count) {
                     for (int x=0; x<response.transactionData.enabledPayments.count; x++) {
                         for (int i = 0; i<self.paymentList.count; i++) {
                             MidtransPaymentListModel *paymentmodel= [[MidtransPaymentListModel alloc]initWithDictionary:self.paymentList[i]];
                             if ([self.paymentRequestResponse.transactionData.enabledPayments[x] isEqualToString:paymentmodel.localPaymentIdentifier]) {
                                 [self.paymentMethodList addObject:paymentmodel];
                             }
                         }
                     }
                 }
                 [self.tableView reloadData];
    
             }
             else {
                 //todo what should happens when payment request is failed;
             }
         }];

Response: 
{
    merchantData =     {
    };
    transactionData =     {
        enabledPayments =         (
        );
        itemDetails =         (
        );
    };
}

**Comment by vanbungkring** [comment]
hi @EonKid  what version of sdk  do you use?

**Comment by EonKid** [comment]
pod 'MidtransKit', '~> 1.0'
pod 'MidtransCoreKit', '~> 1.0'

I am using your provided example code

**Comment by vanbungkring** [comment]
@EonKid  can you remove `1.0` and do pod install then pod update again?

**Comment by EonKid** [comment]
But in implementation of project i have removed the version number and installled the sdk without mentioning the sdk version.

**Comment by jukiginanjar** [comment]
Our latest SDK should be v1.0.14

Maybe it was cached issue, you can try clear your cache first https://gist.github.com/mbinna/4202236

or you can update your cocoapods version

@EonKid
