### ISSUE TITLE
Not open in Xcode 7.3

### ISSUE THREAD

**Issue by Rushabh5** [veritrans/Veritrans-ios-sdk#130]
Hello,

I am integrating SDK but when i am open in Xcode at that time giving me error to open in Xcode 8.

**Error.
FrontView.xib: The document “(null)” requires Xcode 8.0 or later.**

So please suggest me which version i am using so i can open in Xcode 7.3

Thanks.

**Comment by dindatisi** [comment]
Hi @Rushabh5 please update your Xcode into Xcode 8.0 as our SDK requires that version as minimum version. Thanks

**Comment by jukiginanjar** [comment]
You cannot open our SDK project with Xcode 7.3, use XCode 8 or later

If you just want to install it to your project, you can use cocoapods @Rushabh5
