### ISSUE TITLE
Unable to init with customer detail with custom User_id for transaction

### ISSUE THREAD

**Issue by andiesupriyatna** [veritrans/Veritrans-ios-sdk#169]
Hi Midtrans,

I'm andie, IOS Dev from PT Berkah Kreasindo Digital
I have problem to init customer detail with my custom user ID,
it'll be use by merchant server to check transaction  with amount and user ID.
for now the SDK always send user id randomly 
I'm using swift 2.3

and pardon me, I had to add new init in midtrans costumer detail.m Please find my screenshot below
![screen shot 2017-01-20 at 11 19 48 am](https://cloud.githubusercontent.com/assets/24538662/22323237/1ac5e9c2-e3d4-11e6-860e-985bfe3cfcd6.png)

do you have another solution for this?

Thank you

**Comment by vanbungkring** [comment]
halo @andiesupriyatna  let my awesome partner @jukiginanjar  guide you :)

**Comment by andiesupriyatna** [comment]
hi @jukiginanjar any solution for this issue?

**Comment by jukiginanjar** [comment]
so you want to custom your own `customer_id` @andiesupriyatna ?

**Comment by andiesupriyatna** [comment]
correct @jukiginanjar , 
I want to custom my `customer_id` for merchant backend to match the transaction from mistranslation and front end beside match 
so as far I research, I create method in picture above.

**Comment by jukiginanjar** [comment]
actually you don't need to implement new init method, just set the property after initialisation, like `customer.customerIdentifier = @"custom identifier";` @andiesupriyatna

**Comment by jukiginanjar** [comment]
if you don't have anymore question i'll just close this issue @andiesupriyatna
