### ISSUE TITLE
Missing redirection URL

### ISSUE THREAD

**Issue by anandrajr** [veritrans/Veritrans-ios-sdk#206]
Hi,

Im Anand, iOS Developer, Sephora Digital.

When I try to generateToken in swift, I found that it doesn't return me the redirection URL, Is that an issue or the new API changes don't require 3DS authentication? 

Please find my code:

**OBJ-C Code:**

`[[MidtransClient shared] generateToken:tokenRequest completion:^(NSString *token, NSString *redirectURL, NSError *error) {
                 if (error) {
                 //handle error
                 } else {
                 }
                 }];`

**SWIFT:**

`MidtransClient.shared().generateToken(tokenRequest!, completion: { (token, error) in
                    if error == nil {
                        //use the card token
                    } else {
                        //handle error
                    }
                })`

Thanks,
Anand

**Comment by jukiginanjar** [comment]
@anandrajr did you set the `CC_CONFIG.secure3DEnabled` to `true` ?

**Comment by anandrajr** [comment]
@jukiginanjar Yes. But the method _(generateToken)_ returns only 2 values _(token & error)_.

**Comment by jukiginanjar** [comment]
@anandrajr oh I see, we didn't return the URL, because we already handle the 3ds webview validation.

do you still need the URL?

**Comment by anandrajr** [comment]
@jukiginanjar Yes. Because we using custom UI. So I hope that I should handle the 3ds webview right?

**Comment by jukiginanjar** [comment]
@anandrajr for now, unfortunately we cannot provide you the redirect URL, except you do the tokenize request with your own function. anyway thanks with your report, we'll refine the function (not only the function actually) but not in the near future.

**Comment by anandrajr** [comment]
@jukiginanjar "except you do the tokenize request with your own function"

Can you provide sample? or is there any link?

**Comment by jukiginanjar** [comment]
you can see here on [midtrans doc](https://api-docs.midtrans.com/#api-methods) for tokenizing credit card information.

Or see `MidtransClient.m` in source code of the SDK, this function 

```
- (void)generateToken:(MidtransTokenizeRequest *_Nonnull)tokenizeRequest
           completion:(void (^_Nullable)(NSString *_Nullable token, NSError *_Nullable error))completion
```

used to generate token

**Comment by anandrajr** [comment]
Ok Thanks.
