### ISSUE TITLE
Warnings when build on XCode

### ISSUE THREAD

**Issue by arieandrian** [veritrans/Veritrans-ios-sdk#277]
Dear Admin,

I found warnings when loaded MidtransKit and MidtransCoreKit into my current project
I tried to change version into 'release/1.4.2' but still "pod update" got files from release 1.4.0
Please find attached image as previewed warnings on XCode

Thanks & Best Regards,

-arie-
<img width="1512" alt="screen shot 2017-05-01 at 12 18 37 am" src="https://cloud.githubusercontent.com/assets/4764491/25566497/e71bd120-2e03-11e7-87fd-ec472047ffea.png">
<img width="1512" alt="screen shot 2017-05-01 at 12 19 30 am" src="https://cloud.githubusercontent.com/assets/4764491/25566498/e77dfe04-2e03-11e7-9814-988e104a1a24.png">

**Comment by vanbungkring** [comment]
hello @arieandrian  its ok for warning, we try to remove it on next release

**Comment by arieandrian** [comment]
Ok thanks @vanbungkring
