### ISSUE TITLE
Setting Default Header when requesting transaction token

### ISSUE THREAD

**Issue by robzimpulse** [veritrans/Veritrans-ios-sdk#298]
Hi, Thanks for providing this awesome library. i just want to ask. can i set the default header when requesting transaction token to merchant server?

thanks

**Comment by vanbungkring** [comment]
@robzimpulse nope, we don't allow that :), or maybe if you want constructor like that, you can create  your own function to generate snap token :)

**Comment by robzimpulse** [comment]
@vanbungkring thanks for the response
