### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=2, address=0x16ceefb8)

### ISSUE THREAD

**Issue by robzimpulse** [veritrans/Veritrans-ios-sdk#302]
Hi... could you help me with this error, i just clone the repo and run the demo project. i selected credit card payment and entered the credit card number. it seems broken when validating credit card type. 

i'm using : 
- XCode Version 9.0 (9A235)
- Swift 

Here some screenshot : 
Device : [Here](https://slack-files.com/T2W5Z10LV-F7A3YAK34-28026f83d4)
XCode : [Here](https://slack-files.com/T2W5Z10LV-F7B0MQNCE-0190a9fa61)

**Comment by vanbungkring** [comment]
Hello @robzimpulse  what pod version of pod version do you use?

**Comment by robzimpulse** [comment]
@vanbungkring currently, i'm using pod version `1.3.1`. could you help me how to resolve it?

**Comment by vanbungkring** [comment]
pls do `pod update` :) to get latest version

**Comment by robzimpulse** [comment]
@vanbungkring do you mean my cocoapods version ? i'm not quite catch your point.
i also try your suggestion by updating pod udate but the issues still appear.

**Comment by vanbungkring** [comment]
@robzimpulse  in the project, pls do `pod update`, current version is `1.7.2.5`
pod 'MidtransCoreKit', '~> 1.7'
pod 'MidtransKit', '~> 1.7'

**Comment by robzimpulse** [comment]
@vanbungkring i see.  thanks
