### ISSUE TITLE
I received error payment

### ISSUE THREAD

**Issue by cavoixanh** [veritrans/Veritrans-ios-sdk#330]
When I try debug in SDK, response is 402 ("No MID/TID for this transaction") when call API: https://api.sandbox.veritrans.co.id/v2/token with param : {
    bank = maybank;
    "card_cvv" = 123;
    "card_exp_month" = 01;
    "card_exp_year" = 20;
    "card_number" = 4811111111111114;
    "card_type" = Visa;
    channel = migs;
    "client_key" = "VT-client-zh23zFHOQIQTWBVF";
    "gross_amount" = 3300000;
    secure = true;
}

My config Midtrans code(Swift 4) is 

MidtransCreditCardConfig.shared().paymentType = .oneclick MidtransCreditCardConfig.shared().tokenStorageEnabled = true
MidtransCreditCardConfig.shared().saveCardEnabled = true
MidtransCreditCardConfig.shared().secure3DEnabled = true
MidtransConfig.shared().customPaymentChannels = cartViewModel.enable_payment (my list enable_payment from my server)

What is wrong? thank you

**Comment by rizdaprasetya** [comment]
402 is because the account's `maybank` acquiring is not yet activated.
Midtrans will need to activate it first.

Further conversation will be done in Slack because we will need to know which account.
Thanks.

**Comment by cavoixanh** [comment]
Hi sir,
I am using account:  hasiholan.purba@acommerce.asia 
Please help me check it!
Thank you very much

**Comment by cavoixanh** [comment]
I fixed this issue with bca bank. Thank you for your support
