### ISSUE TITLE
Crash after tap the pay button when credit card payment method picked

### ISSUE THREAD

**Issue by ariefzainuri** [veritrans/Veritrans-ios-sdk#451]
Permisi, saya mengalami kendala ketika sudah masuk ke payment screen, dan memilih credit card pada list payment, setelah mengisi card number, expired date, dan cvv, lalu menekan tombol pay button, setelah itu berpindah screen loading tidak lama setelah itu crash dengan error [__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'.

regards

**Comment by uziwuzzy** [comment]
bisa di share kode cara implementasinya @ariefzainuri ?
