### ISSUE TITLE
Gopay payment is not supported

### ISSUE THREAD

**Issue by gio93ivan** [veritrans/Veritrans-ios-sdk#453]
I am using the latest version in Cocoapods, which is version 1.14.7, but when I try to pay using gopay, it prompts out that my device doesn't have any gojek app despite having one on my device

Expected result: it should detect that my device having gojek app and proceed to pay with gopay.

**Comment by Seven163** [comment]
@gio93ivan It's same with me. And I check it will go to gojek website for Android.

**Comment by uziwuzzy** [comment]
You need to add the gojek scheme below into the info.plist file of your project.

```
<key>LSApplicationQueriesSchemes</key>
<array>
<string>gojek</string>
</array>
```

**Comment by Seven163** [comment]
@uziwuzzy Thanks. I've solved it.
