### ISSUE TITLE
Transaction is unsuccessfull

### ISSUE THREAD

**Issue by navaranjithavelladurai** [veritrans/Veritrans-ios-sdk#459]
Transaction is unsuccessfull, Please try again with another card or with different payment mode

<img width="293" alt="Screenshot 2019-07-06 at 4 31 20 PM" src="https://user-images.githubusercontent.com/43840824/60755310-923bfc80-a00b-11e9-83c9-81de4755e213.png">

Here i used the sandbox environment, to get the access token
xxxxxxx - Client Key
 MidtransConfig.shared().setClientKey("xxxxxxx", environment: .sandbox, merchantServerURL: "https://rakawm-snap.herokuapp.com")

**Comment by navaranjithavelladurai** [comment]
**Here I Updated my snapshot here**

**func midTrainsParm() {
        
        let shippingAddress = MidtransAddress()
        
        let customerDetail = MidtransCustomerDetails.init(firstName: userData.first_name, lastName:
            userData.last_name, email: userData.email, phone: userData.mobile, shippingAddress: shippingAddress,
                                billingAddress: shippingAddress)
        
        let myInteger = Int(amountStr)
        
        let myNumber = NSNumber(value:myInteger)
        
        var randomOrderID = "TRNX"
        
        randomOrderID.append(randomString(length: 6))
        
        let transactionDetail = MidtransTransactionDetails.init(orderID: randomOrderID, andGrossAmount:myNumber , andCurrency: MidtransCurrency.IDR)
        
        MidtransMerchantClient.shared().requestTransactionToken(with: transactionDetail!,
                                                                itemDetails: [MidtransItemDetail](), customerDetails: customerDetail) { (response, error) in
                                                                    
                                                                    if (response != nil) {
                                                                        let vc = MidtransUIPaymentViewController.init(token: response)
                                                                        vc?.paymentDelegate = self
                                                                        self.present(vc!, animated: true, completion: nil)
                                                                    }
                                                                    else {
                                                                        print(error as Any)
                                                                    }
        }
    }**

**Comment by jukiginanjar** [comment]
what's the value of your expiration date and cvv?

**Comment by navaranjithavelladurai** [comment]
Thank you for your response jukiginanjar 
 expiration date - 01/20 & cvv - 123

**Comment by jukiginanjar** [comment]
ah, you're using our merchant servers which will not work with your client key

**Comment by navaranjithavelladurai** [comment]
Ok then what will we do for our end ?

Could you please give the suggestion

**Comment by jukiginanjar** [comment]
Implement your own merchant server, this is the example [https://github.com/rizdaprasetya/midtrans-mobile-merchant-server--php-sample-](url)

**Comment by navaranjithavelladurai** [comment]
<img width="1158" alt="Screenshot 2019-07-06 at 6 12 03 PM" src="https://user-images.githubusercontent.com/43840824/60756297-9b33ca80-a019-11e9-96c6-ee37a250a269.png">
Url doesn't have anything

**Comment by jukiginanjar** [comment]
https://github.com/rizdaprasetya/midtrans-mobile-merchant-server--php-sample-
