### ISSUE TITLE
how can I automatic back my host app?

### ISSUE THREAD

**Issue by wooseng** [veritrans/Veritrans-ios-sdk#468]
when I jump to Gojek and payment successful, it can't automatic jump to my host app, what should I do?

**Comment by uziwuzzy** [comment]
you need to implement the deeplink callback by adding your app url schemes.
Go to _Project Settings_ -> _Info_, and add inside _The URL Types_ section a new URL scheme. Add something of the sort of `warungpedia`.
Afterwards, you need to configure it in the sdk based on your url scheme name. `MidtransConfig.shared()?.callbackSchemeURL = "warungpedia://"`

**Comment by wooseng** [comment]
**URL Scheme**
<img width="671" alt="1" src="https://user-images.githubusercontent.com/22250024/65300229-54c82380-dba5-11e9-8f0d-b8a1f41eb498.png">

**AppDelegate**
`MidtransConfig.shared()?.callbackSchemeURL = "midtrans.shaoxi://"`

**MyViewController**
```
MidtransMerchantClient.shared().requestTransacation(withCurrentToken: token) { [weak self] response, _ in
            guard let vc = MidtransUIPaymentViewController(token: response) else {
                return
            }
            vc.paymentDelegate = self
            self?.present(vc, animated: true, completion: nil)
        }
```

I've done that, but it's no use.

Is there anything else I need to do?

**Comment by uziwuzzy** [comment]
you need to add the sdk config _MidtransConfig.shared()?.callbackSchemeURL = "midtrans.shaoxi://"_

**Comment by wooseng** [comment]
yes, I had add the sdk config `MidtransConfig.shared()?.callbackSchemeURL = "midtrans.shaoxi://"`, but it still doesn't work.

I use `MidtransMerchantClient.shared().requestTransacation(withCurrentToken: token)` to get `MidtransTransactionTokenResponse` object, but I didn't find a place to use the `callbackSchemeURL` in the relevant source code. I don't know if I'm using the wrong method.

**Comment by uziwuzzy** [comment]
your code above is correct, you can just put it in the appdelegate same with other sdk config like merchant server/client key. It should be working, what's the issue now?

**Comment by wooseng** [comment]
thanks, I hava to try it now. if it still doesn't work, I'll give it back.

**Comment by uziwuzzy** [comment]
Sure, no problem.
