### ISSUE TITLE
UIWebView no longer support with upcoming iOS 13

### ISSUE THREAD

**Issue by bank18651** [veritrans/Veritrans-ios-sdk#469]
UIWebView no longer support with upcoming iOS 13.
Current version is MidtransCoreKit (1.16.0)
Do I have to concern about 3DS because there is UIWebViewDelegate on Midtrans3DSController?
If we need to update SDK version please let me know as soon as possible.

Thank you.

**Comment by agfa555** [comment]
I have the same concern. Can you please let us know ASAP?

**Comment by uziwuzzy** [comment]
We've updated the sdk by replacing UIWebView with WKWebView. Please update to the latest version v1.16.0,  You can seen in here https://github.com/veritrans/Veritrans-ios-sdk/releases/tag/1.16.0
