### ISSUE TITLE
Token response always nil

### ISSUE THREAD

**Issue by hedypamungkas** [veritrans/Veritrans-ios-sdk#470]
Hi Midtrans Team!

I got any issue when generate transaction token. This is my function to generate token, and always get nil in response.tokenId

```
private func tokenGenerator(onSuccess: ((MidtransTransactionTokenResponse) ->Void)?, onError: ((Error?) -> Void)?) {
        MidtransMerchantClient.shared().requestTransactionToken(with: self.transactionDetail, itemDetails: [self.itemDetail], customerDetails: self.customerDetail) { (res, err) in
            if let response = res {
                if response.tokenId == nil {
                    onError?(nil)
                } else {
                    onSuccess?(response)
                }
            } else {
                onError?(err)
            }
        }
    }
```

Before execute this function, I already setClientKey in AppDelegate.swift

**Comment by uziwuzzy** [comment]
are you perhaps requesting the transaction token from backend first?  It seems that you get the token already, If so, change the method, instead requesting transaction token again, use the `MidtransMerchantClient.shared().requestTransacation(withCurrentToken)` method and just pass the token as param

**Comment by hedypamungkas** [comment]
It solved. I put the wrong merchant server url, but when I got the token and success to show up the SNAP/Mobile SDK 

but why SNAP show 0 amount and empty list in payment method in sandbox environment. but smooth and no issue when production environment?

**Comment by uziwuzzy** [comment]
are you using the same merchant server?

**Comment by hedypamungkas** [comment]
Different server

```
#if DEBUG
MidtransConfig.shared()?.setClientKey(serverKey(), environment: .sandbox, merchantServerURL: String.BaseApiUrl)
#else
MidtransConfig.shared()?.setClientKey(serverKey(), environment: .production, merchantServerURL: String.BaseApiUrl)
#endif
```

serverKey() and String.BaseApiUrl already separate value between debug and release

**Comment by uziwuzzy** [comment]
it should be working. Does the screen looks like this?
<img width="504" alt="Screen Shot 2019-10-08 at 18 39 55" src="https://user-images.githubusercontent.com/3756851/66392800-17fc8900-e9fb-11e9-8ca9-a3f09c1ee9f7.png">
It means there's a wrong config. 
Possible causes:
1. Unmatch between environment and the client key and merchant server. Please make sure if it's the correct one for development and production.
2. Wrong implementation on the request url on merchant server, is it correctly requesting to the sandbox? Sometimes people forgot to add `sandbox` in the url.

please make sure to configure correctly.

**Comment by hedypamungkas** [comment]
Thanks.

In fact, any issue in our development server.
Thanks for your support!!
