### ISSUE TITLE
Phone attribute in MidtransCustomerDetails should be optional?

### ISSUE THREAD

**Issue by Firman95** [veritrans/Veritrans-ios-sdk#471]
Hi!

In the documentation, the Customer Detail Information, including the `phone` attribute is optional. When we tried to call this SDK with `phone` set to null, it worked in Android, but it crashed in IOS. 

After further examination, we found out that the cause of the error is in `MidtransCoreKit/MidtransCoreKit/MidtransCustomerDetails.m` file, at line 56. This SDK crashed because it tried to get length from `phone` attribute that is `null`. 

Perhaps you can add an extra check to prevent getting the length of the `null` `phone` attribute?

**Comment by uziwuzzy** [comment]
I tried setting it as `nil`, its working fine. Can I see your implementation?
