### ISSUE TITLE
Swipe down 3DS webview in iOS 13 and completion was not working

### ISSUE THREAD

**Issue by bank18651** [veritrans/Veritrans-ios-sdk#473]
Xcode v.11
iOS 13
MidtransCoreKit (1.16.0)

In Xcode 11 when generate token by **MidtransClient** with 3DS and completion seem not working when swipe view down to dismiss.
This issue might came from sheet modal that presented on iOS 13 in Xcode 11.
For quick fix, Is it possible to force present as full screen from any config?

**Comment by uziwuzzy** [comment]
yes, will update and force the fullscreen for now to fix this issue. Will release this week.

**Comment by uziwuzzy** [comment]
please try updating to v1.16.1, it's been released.

**Comment by bank18651** [comment]
It's working.
Thank you.
