### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString allKeys]: unrecognized selector sent to instance 0xea94762b56b07773'

### ISSUE THREAD

**Issue by vikas100** [veritrans/Veritrans-ios-sdk#477]
Hi,
I am trying to use below function but getting error.      

This is the function:-

  MidtransMerchantClient.shared().requestTransactionToken(with: transactionDetail!, itemDetails: [itemDetail!], customerDetails: customerDetail, customField: [customFieldID], binFilter: nil, blacklistBinFilter: nil, transactionExpireTime: nil) { (response, error) in
            
                        completion(response)
            
        }

Getting Error:- Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString allKeys]: unrecognized selector sent to instance 0xea94762b56b07773'

Note:- If I will pass nil to "customField" then it is working if we will pass array it is crashing.

Best
Vikas

**Comment by uziwuzzy** [comment]
you need to create the array for customField like this:
```
NSMutableArray *arrayOfCustomField = [NSMutableArray new];
[arrayOfCustomField addObject:@{MIDTRANS_CUSTOMFIELD_1:@"someValue"}];       [arrayOfCustomField addObject:@{MIDTRANS_CUSTOMFIELD_2:@"someValue"}];`
```

**Comment by vikas100** [comment]
I want to use below function in Swift.how pass array in customField.
I am passing like -> [String] this (String contain some value). But passing like this getting crashed.

- (void)requestTransactionTokenWithTransactionDetails:(nonnull MidtransTransactionDetails *)transactionDetails
                                          itemDetails:(nullable NSArray<MidtransItemDetail*> *)itemDetails
                                      customerDetails:(nullable MidtransCustomerDetails *)customerDetails
                                          customField:(nullable NSArray *)customField
                                            binFilter:(nullable NSArray *)binFilter
                                   blacklistBinFilter:(nullable NSArray *)blackListBin
                                transactionExpireTime:(nullable MidtransTransactionExpire *)expireTime
                                           completion:(void (^_Nullable)(MidtransTransactionTokenResponse *_Nullable token, NSError *_Nullable error))completion;

**Comment by uziwuzzy** [comment]
this is the swift version to create the array:

```
var arrayOfCustomField: [Any] = []
arrayOfCustomField.append([MIDTRANS_CUSTOMFIELD_1: "someValue"])
arrayOfCustomField.append([MIDTRANS_CUSTOMFIELD_2: "someValue"])

```
then pass it to the parameter of `customField` in the requestTransaction function

**Comment by vikas100** [comment]
Thank You
