### ISSUE TITLE
App called -statusBar or -statusBarWindow on UIApplication

### ISSUE THREAD

**Issue by efrizalde** [veritrans/Veritrans-ios-sdk#483]
Permisi mau tanya, saya ada masalah saat ingin melakukan transaksi.

untuk code saat ingin memanggil UInya ini
![image](https://user-images.githubusercontent.com/38771472/72133960-4badcd00-33b5-11ea-915c-e6562430281a.png)

saat saya mau mulai transaksi token dapat diambil namun setelah itu muncul error ini
![image](https://user-images.githubusercontent.com/38771472/72134093-ab0bdd00-33b5-11ea-92dd-a70af1201bb9.png)

Mau tanya kira kira ada salahnya dimana ya? saya menggunakan flutter, dan memanggil view swift

Thanks

**Comment by uziwuzzy** [comment]
pakai versi brp ya? itu kemungkinan error ios 13, coba di update k versi sdk terbaru.

**Comment by efrizalde** [comment]
Sudah saya update, tapi masih dapat error yg sama

saya cek pakai v1.14.7
![image](https://user-images.githubusercontent.com/38771472/72136890-5ddf3980-33bc-11ea-8c36-3c08060e9631.png)

**Comment by uziwuzzy** [comment]
hmm kurang tau jg kalo issuenya di flutter, soalnya kita ga support selain native, dan ini ga reproduceable di di native code.

**Comment by efrizalde** [comment]
Oke thanks, sudah bisa setelah saya update ke v1.16.2, sebelumnya saya pakai "pod update" mentok di v1.14.7 jadi saya kira sudah terbaru.
