### ISSUE TITLE
Reference to UIWebview are present in the framework code

### ISSUE THREAD

**Issue by keshavamurthy1** [veritrans/Veritrans-ios-sdk#486]
Hello team,
Im using MidtransCoreKit in my project, since few release apple started sending warning messages to me whenever I upload the build to app store for review, which says below:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information

As I did investigation and found out that only in MidtransCoreKit I could able to see some keywords **UIWebViewDelegate, uiwebview** due to which I might be getting the warnings from apple.

Do you have any plan to remove these keywords as apple says they stop accepting submissions if something like in the code?

Regards
Keshav

**Comment by uziwuzzy** [comment]
hi, what version are you using? I think the latest version should not include any UIwebview, the only thing left is only the #pragma mark comment.

**Comment by keshavamurthy1** [comment]
Hi 
Thanks for the quick response.


We are using 1.16.0

pod 'MidtransCoreKit','~> 1.16.0’

Yes, I too found that UIWebview is only in  #pragma mark comment.

Seems like Apple automation system is detected those as well and sending us warning every time we upload the build for review.

Are you guys going to update the  #pragma mark and comments any time soon?

Regards
Keshav

**Comment by uziwuzzy** [comment]
Sure, will remove it together with the next updated version. Thanks for the feedback.

**Comment by j-elmer123** [comment]
Hi, I got the same problem here and the message has been updated by Apple that they won't accept submissions of new apps as of **April 30, 2020** if the app still use **UIWebView**

> ITMS-90809: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by uziwuzzy** [comment]
we don't use UIWebview anymore, and already migrate to use wkwebview months ago. So there should be no issue on the usage and submission.  
The problem seems caused only on the pragma mark comment, we'll remove it in the next release, ETA next week.

**Comment by j-elmer123** [comment]
Hi @uziwuzzy may I know if the pragma mark comment already removed?

Regards,

> we don't use UIWebview anymore, and already migrate to use wkwebview months ago. So there should be no issue on the usage and submission.
> The problem seems caused only on the pragma mark comment, we'll remove it in the next release, ETA next week.

**Comment by j-elmer123** [comment]
Hi @uziwuzzy I think this issue already solved https://github.com/veritrans/Veritrans-ios-sdk/commit/a23c3f4773c239db26ecd261dd0e7b5472c24e53 right?

**Comment by uziwuzzy** [comment]
correct, it's solved there.
