### ISSUE TITLE
Didn't get token after requestTransactionToken

### ISSUE THREAD

**Issue by calistabertha** [veritrans/Veritrans-ios-sdk#488]
Hi team. 
I used the MidtransKit 1.16.2 and after `requestTransactionToken`, I didn't get the tokenID. but the backend gives a token response when hit endpoint /charge. This is my code 
 ```
guard let itemDetail = MidtransItemDetail(itemID: "b50", name: "TestMidtrans", price: 200, quantity: 1) else { return }
 let billingAddress = MidtransAddress(firstName: "", lastName: "", phone: "", address: "", city: "", postalCode: "", countryCode: "")
 let customerDetail = MidtransCustomerDetails(
            firstName: UserManager.instance.getUser().name,
            lastName: UserManager.instance.getUser().name,
            email: UserManager.instance.getUser().emails.first?.address,
            phone: UserManager.instance.getUser().phones.first?.number,
            shippingAddress: billingAddress,
            billingAddress: billingAddress
        )

 guard let transactionDetail = MidtransTransactionDetails(orderID: "50", andGrossAmount: 200) else { return }
  MidtransMerchantClient.shared().requestTransactionToken(with: transactionDetail, itemDetails: [itemDetail], customerDetails: customerDetail) { (token, error) in
            if (token != nil) {
                guard let midtransUI = MidtransUIPaymentViewController(token: token, andPaymentFeature: .MidtransPaymentFeatureBankTransfer) else { return }
                self.delegate?.invoiceOtherPayment(midtransUI)
            } else {
                print("error \(error)")
            }
        }
    }

```

![Simulator Screen Shot - iPhone X - 2020-04-28 at 12 44 49](https://user-images.githubusercontent.com/27281507/80451514-41a4df80-894e-11ea-84c0-b9471eb0732c.png)

and this is the response from backend :

```
{
  "status" : 200,
  "content" : {
    "error_messages" : null,
    "redirect_url" : "https://app.sandbox.midtrans.com/snap/v2/vtweb/de015d2e-f8f4-461e-9e1b-b3dde38548cc",
    "status_code" : "201",
    "token" : "de015d2e-f8f4-461e-9e1b-b3dde38548cc"
  },
  "request_id" : "0e2221a4ec1344fdde57f1db6f96e54d",
  "error" : null
}
```

can you help me? Is there something wrong with the configuration?

**Comment by uziwuzzy** [comment]
Your backend should give you the token on `requestTransactionToken`. You need to make sure the response that you get from the backend is correctly given to the method. Because once you get the token, you should be able to pass it and start transacting.
 Try enable the logger with this code `MidtransNetworkLogger.shared.startLogging` in your viewdidload or in appdelegate to help you debug the networking calls.

**Comment by calistabertha** [comment]
I see. We already solve the problem. The solution is our backend should give `token_id`, so the SDK can read it as token. Thanks!
