### ISSUE TITLE
Manual integration of MidtransKit not supported

### ISSUE THREAD

**Issue by lalkrishna** [veritrans/Veritrans-ios-sdk#514]
Manual integration throws me below error while archiving.

> was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file

-------------

I can able to manage this by adding:

- Project settings -> Select Framework Target -> Build settings
 add `-fembed-bitcode` in **Other C Flags**

- click + Button -> Add User-Defined Setting
Key: **BITCODE_GENERATION_MODE**
value: **bitcode**

> Note: For `MidtransCoreKit`, Set **Build Active Architectures Only** to **Yes** in Build settings.

### Steps for Building Universal Framework:
- Build framework for Simulator OS (Select simulator as target device) and iPhone OS(Any iOS Device (arm64)).
Select Framework scheme -> Build for Profiling (Release)
- Project Navigator -> Open 'Products' folder -> Right click show in Finder.
- I Just copied `Release-iphoneos` and `Release-iphonesimulator` folders to desktop.
- Use lipo to aggregate both these architectures
 (I just duplicated _Release-iphoneos_ folder and renamed it to _Release-Universal_
```
lipo -create /Users/username/Desktop/Lib/Release-iphoneos/MidtransKit.framework/MidtransKit /Users/username/Desktop/Lib/Release-iphonesimulator/MidtransKit.framework/MidtransKit -output /Users/username/Desktop/Lib/Release-Universal/MidtransKit.framework/MidtransKit

lipo -create /Users/username/Desktop/Lib/Release-iphoneos/MidtransCoreKit.framework/MidtransCoreKit /Users/username/Desktop/Lib/Release-iphonesimulator/MidtransCoreKit.framework/MidtransCoreKit -output /Users/username/Desktop/Lib/Release-Universal/MidtransCoreKit.framework/MidtransCoreKit
```

- User .framework file in Release-Universal folder.

---------------
### In Client side Project:

- Select Build Phases -> Click + Button -> **New Run Script Phase**
Add below code.

```
# Type a script or drag a script file from your workspace to insert its path.
# skip if we run in debug
if [ "$CONFIGURATION" == "Debug" ]; then
echo "Skip frameworks cleaning in debug version"
exit 0
fi

APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done

```

**Comment by lalkrishna** [comment]
Now im using xcframework as Xcode 12.3 no longer support universal frameworks.

Link: https://gist.github.com/lalkrishna/c1b33cba4dbacddbc1ecc9d619877c42

**Comment by uziwuzzy** [comment]
our SPM uses xcframework, so you can check our `Package.Swift` to see the url of the latest xcframework. You can also go to the release page here and download the xcframework zip file manually
