### ISSUE TITLE
Custom Field

### ISSUE THREAD

**Issue by ntaloventi** [veritrans/Veritrans-ios-sdk#529]
Dear Guys, 
Need Help to use Custom Field in Swift
Thanks

**Comment by uziwuzzy** [comment]
you can do something like this


        let customFieldArray = [
            [MIDTRANS_CUSTOMFIELD_1:"someValue"],
            [MIDTRANS_CUSTOMFIELD_2:"someValue"],
            [MIDTRANS_CUSTOMFIELD_3:"someValue"]
        ]
        MidtransMerchantClient.shared().requestTransactionToken(with: transactionDetail!, itemDetails: [itemJacket!, itemPants!], customerDetails: customerDetail, customField: customFieldArray, binFilter: nil, blacklistBinFilter: nil, transactionExpireTime: nil) { (response, error) in
            if (response != nil) {
                //present payment page
                let vc = MidtransUIPaymentViewController.init(token: response)
                vc?.paymentDelegate = self
                self.present(vc!, animated: true, completion: nil)
            }
            else {
                print("error \(error!)")
            }
        }
