### ISSUE TITLE
Tapping "Pay Now" button multiple times ended up in failed

### ISSUE THREAD

**Issue by lalkrishna** [veritrans/Veritrans-ios-sdk#542]
Tapping "Pay Now" button multiple times ended up in failed and returned with Message:

> Pesanan anda telah dibayar (English translation: Your order has been paid)

To reproduce the issue:

- Choose "Credit Card" payment method
- Enter card details
- Tap "Pay Now" rapidly multiple times.

**Comment by uziwuzzy** [comment]
Yes, we have found this issue, and the fix will be availabe on the next release, ETA early July.

**Comment by uziwuzzy** [comment]
fixed starting from sdk v1.19.0 https://github.com/veritrans/Veritrans-ios-sdk/releases/tag/1.19.0
