### ISSUE TITLE
swipe-layout-1.1.0 troible with sdk 1.19.1 version

### ISSUE THREAD

**Issue by laziena** [veritrans/Veritrans-ios-sdk#550]
FAILURE: Build completed with 9 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDevelopmentDebug'.
> Could not resolve all files for configuration ':app:developmentDebugCompileClasspath'.
   > Could not find :swipe-layout-1.1.0:.
     Required by:
         project :app > com.midtrans:uikit:1.29.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:dataBindingMergeGenClassesDevelopmentDebug'.
> Could not resolve all files for configuration ':app:developmentDebugCompileClasspath'.
   > Could not find :swipe-layout-1.1.0:.
     Required by:
         project :app > com.midtrans:uikit:1.29.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDevelopmentDebugResources'.
> Could not resolve all files for configuration ':app:developmentDebugRuntimeClasspath'.
   > Could not find :swipe-layout-1.1.0:.
     Required by:
         project :app > com.midtrans:uikit:1.29.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDevelopmentDebugAarMetadata'.
> Could not resolve all files for configuration ':app:developmentDebugRuntimeClasspath'.
   > Could not find :swipe-layout-1.1.0:.
     Required by:
         project :app > com.midtrans:uikit:1.29.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDevelopmentDebugMainManifest'.
> Could not resolve all files for configuration ':app:developmentDebugRuntimeClasspath'.
   > Could not find :swipe-layout-1.1.0:.
     Required by:
         project :app > com.midtrans:uikit:1.29.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDevelopmentDebugAssets'.
> Could not resolve all files for configuration ':app:developmentDebugRuntimeClasspath'.
   > Could not find :swipe-layout-1.1.0:.
     Required by:
         project :app > com.midtrans:uikit:1.29.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

7: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDevelopmentDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:developmentDebugRuntimeClasspath'.
   > Could not find :swipe-layout-1.1.0:.
     Required by:
         project :app > com.midtrans:uikit:1.29.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

8: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:desugarDevelopmentDebugFileDependencies'.
> Could not resolve all files for configuration ':app:developmentDebugRuntimeClasspath'.
   > Could not find :swipe-layout-1.1.0:.
     Required by:
         project :app > com.midtrans:uikit:1.29.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

9: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDevelopmentDebugNativeLibs'.
> Could not resolve all files for configuration ':app:developmentDebugRuntimeClasspath'.
   > Could not find :swipe-layout-1.1.0:.
     Required by:
         project :app > com.midtrans:uikit:1.29.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

**Comment by uziwuzzy** [comment]
this is android issue, not ios
