### ISSUE TITLE
No visible @interface for 'UITableView' declares the selector 'setSectionHeaderTopPadding:'

### ISSUE THREAD

**Issue by faisalarip** [veritrans/Veritrans-ios-sdk#562]
i have an error `No visible @interface for 'UITableView' declares the selector 'setSectionHeaderTopPadding:'` in VTPaymentListView.m, the error happened when i try to running the xcode after fresh pod installed. i put sdk MidtransCoreKit (1.20.2) and MidtransKit (1.20.2) in pod file

Tools: 
XCode 12.4, Swift 5

<img width="836" alt="Screen Shot 2022-03-26 at 15 51 11" src="https://user-images.githubusercontent.com/59595501/160232143-c79be14d-68a5-418e-be63-29457e24de94.png">

**Comment by uziwuzzy** [comment]
the api is available for ios 15, since your xcode is version 12, it can only run ios 14 and earlier, thus causes this error. Please update to xcode 13.
