### ISSUE TITLE
Implement Google Analytic 4 

### ISSUE THREAD

**Issue by Rostadhi** [veritrans/Veritrans-ios-sdk#566]
Dear Midtrans Team.

Can i implement Google Analytic 4 for tracking the price etc.. from order/transaction detail but skipping the backend process and with custom success transaction page ?

Thankyou

**Comment by uziwuzzy** [comment]
you can hide the transaction status page by calling something likethis `MidtransUIConfiguration.shared.hideStatusPage` , and implement your own. However for analytics, you can only implement it inside the code that you can control.
