### ISSUE TITLE
bugs setelah proses 3D secure

### ISSUE THREAD

**Issue by sawijaya** [veritrans/Veritrans-ios-sdk#80]
setelah proses 3D Secure method payWithToken dipanggil dan terjadi crash, kemungkinan karna di dalam class VTPaymentCreditCard ada attribute tokenId masih nil. atau ada kesalahan yang lain selain itu. mohon perbaikannya.

**Comment by jukiginanjar** [comment]
@sawijaya ini error nya kadang2 atau terus terjadi?

**Comment by sawijaya** [comment]
@jukiginanjar terus terjadi, itu saya cb dari demo yang ada di github.

**Comment by jukiginanjar** [comment]
@sawijaya bisa coba dulu demo di github yg ada di branch `development` ?

**Comment by jukiginanjar** [comment]
@sawijaya demo nya yang di coba di branch `master`? 

silahkan coba lagi demo nya, saya sudah update branch `master`, sudah saya coba juga dan works fine

thanks
