### ISSUE TITLE
Crash With  Default VTPaymentViewController 

### ISSUE THREAD

**Issue by paperclipz** [veritrans/Veritrans-ios-sdk#81]
Hi, It seems that I used cocoapods to install there is missing files (MidtransResources).
While for demo version it is not using cocoapods and the files is there. Kindly assist with this issue.

**Comment by vanbungkring** [comment]
hi @paperclipz  what pods version do you use? 1.0?
do you use `pod 'MidtransKit'` and `pod 'MidtransCoreKit'`

**Comment by paperclipz** [comment]
Hi Arie,

Thanks for the prompt reply. I am using     pod 'MidtransKit'
cocoapod version is 1.0.1.

Cheers,
Evan

**Comment by paperclipz** [comment]
Hi Arie,

The error message return is




* *** Terminating app due to uncaught exception
'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle:
'NSBundle
</var/containers/Bundle/Application/58AE6ABE-2DB2-4A09-BDDD-747EFAC20A48/->
(loaded)' with name 'VTPaymentListController''.*

Cheers,
Evan

**Comment by jukiginanjar** [comment]
@paperclipz i've updated the SDK on cocoapods, the new one is version 0.2.1, please use that version

Thanks

**Comment by paperclipz** [comment]
@jukiginanjar , I had reinstall the pod and cant find it else where for the resources. can you guide me on where can i get the latest pod? thanks

**Comment by jukiginanjar** [comment]
can you share your podfile @paperclipz ?

**Comment by paperclipz** [comment]
i am inputting 
    pod 'MidtransKit'
do i need to set the version on it?

**Comment by jukiginanjar** [comment]
nope, that should be fine

or maybe you need to remove pod cache first

these code is how to reset the pod cache

```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by paperclipz** [comment]
Thank you very much @jukiginanjar . Its fix now.

**Comment by jukiginanjar** [comment]
Glad to hear that, i'll just close this issue then, if you have anymore problem with the SDK just create new issue

thanks
